// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byaniufkrhtwyqgoekjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5YW5pdWZrcmh0d3lxZ29la2psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDkxMzYsImV4cCI6MjA2MDYyNTEzNn0.98N5Jr49GhEpOJsAuQiAiHpnggBXTdYiCcS7TzFy8N0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);